config-version: 1.3.52

# Illegal items configuration
illegal-items:
  blocks:
    - CHAIN_COMMAND_BLOCK
    - COMMAND_BLOCK
    - COMMAND_BLOCK_MINECART
    - REPEATING_COMMAND_BLOCK
    - BEDROCK
    - BARRIER
    - STRUCTURE_BLOCK
    - STRUCTURE_VOID
    - NETHER_PORTAL
    - LIGHT
    - END_PORTAL_FRAME
    - END_PORTAL
    - SPAWNER
  items:

# Chunk limiter configuration
chunk-limiter:
  limits:
    CHEST: 400
    TRAPPED_CHEST: 400
    TNT: 200

  messages:
    block-limit-exceeded: You cannot place more than {limit} {block} blocks in this chunk.


# Command whitelist configuration
command-whitelist:
  enabled: true
  commands:
    - help
    - vote
    - joindate
    - kill
    - discord
    - togglechat
    - toggleconnectionmsgs
    - toggletells
    - togglewhispering
    - toggleprivatemsgs
    - ignore
    - ignorelist
    - ignorehard
    - toggledeathmsg
    - dmt
    - worldstats
    - playtime
    - stats
    - tps
    - msg
    - whisper
    - w
    - m
    - t
    - pm
    - tell
    - r
    - reply
    - last
    - kill
    - shop
    - skin

# Command blacklist configuration
command-blacklist:
  enabled: true
  commands:
    - op
    - deop
    - plugins
    - pl
    - bukkit:plugins
    - bukkit:pl
    - bukkit:?
    - bukkit:help
    - .plugins



# Additional configurations
additional-configs:
  check-interval: 10 # Time in seconds between periodic checks
  inventory-scan-depth: 3 # Depth of inventory scanning, affects how many nested inventories are checked

removal-options:
  remove-illegal-items: true
  clean-shulkers-on-place: true
  notify-player-on-illegal-placement: true


messages:
  illegal-item-placement:
    title: "&cIllegal Block!"
    subtitle: "&cThis is an illegal item!"
  illegal-item-interaction:
    title: "&cIllegal Item!"
    subtitle: "&cYou tried to interact with an illegal item: %item%"
  illegal-item-movement:
    title: "&cIllegal Item!"
    subtitle: "&cContainer tried to move an illegal item: %item%"
  illegal-item-removal:
    title: "&cIllegal Items Removed!"
    subtitle: "&cIllegal items were removed from your inventory."
  admin-alert: "&c%player% tried to interact with an illegal item: %item%"


# Deop on leave configuration
deop-on-leave:
  enabled: true
  whitelist:
    enabled: false
    players:
      - playername1
      - playername2
  teleport:
    world: world
    x: 0.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  message: '&cYou have been deopped, your inventory cleared, and you have been teleported to the spawn point.'


# Admin alerts configuration
admin-alerts:
  enabled: true
  permission: oaexploits.alerts
  cooldown: 60 # seconds between alerts to avoid spam

# Logging settings configuration
log-settings:
  log-illegal-item-actions: true
  log-file: logs/oaexploits.log
  log-level: WARNING


  # Debug mode configuration to see what commands people are executing
  debug-mode: false
