name: Oaexploits
version: 1.3.52
main: fanlim.dev.oaexploits.Oaexploits
api-version: 1.13
commands:
  oaexploits:
    description: Main command for Oaexploits
    aliases: [oae, oaexp]
    usage: /<command> reload
    permission: oaexploits.reload
  worldstats:
    description: Command to display world stats
  playtime:
    description: Shows the playtime of a player
    usage: /<command> <player>
permissions:
  oaexploits.reload:
    description: Allows the player to reload the Oaexploits configuration
    default: op
  oaexploits.alerts:
    description: Allows the player to receive alerts from Oaexploits
    default: op
